/* Generated by ops/make_deploy.py. Edit ops/make_deploy.py, not this. */
window.INVITE_CONFIG = {
  DATA_SOURCE: 'sheet',
  ACTIVE_VARIANT: 'line-up',
  HONOUR_PER_GUEST_VARIANT: false,
  COMPANIONS: 3,
  APPLY_BASE: 'https://contextful.com/apply/',
  API_BASE: 'https://contextful.com',
  APPLY_FALLBACK_TOKEN: '',
  WEB_APP_URL: '',
  CONTENT_BASE: 'content/build/',
  CONTENT_FILES: { 'line-up': 'the-line-up.html', 'room': 'the-room.html' },
  HEADER_NAME: 'full',
  TRACKING: false,
  MOCK_FALLBACK_URL: 'data/guests.json',
  LOCALE: 'en',
};
